# Code Generated by Sidekick is for learning and experimentation purposes only.
import argparse
import hashlib
import ipaddress
import random
import re
import socket
import ssl
import string
import sys
import time
import uuid
from dataclasses import dataclass
from urllib.parse import urlparse, urlunparse

import requests


INGRESS_FINGERPRINTS = {
    "ingress-nginx": [("server", re.compile(r"\bingress-nginx\b|\bnginx\b", re.I))],
    "traefik": [("server", re.compile(r"\btraefik\b", re.I))],
    "envoy/istio": [("server", re.compile(r"\benvoy\b|\bistio\b", re.I))],
    "kong": [("server", re.compile(r"\bkong\b", re.I))],
    "haproxy": [("server", re.compile(r"\bhaproxy\b", re.I))],
    "aws-elb/alb": [("server", re.compile(r"\bawselb\b|\belb\b|\balb\b", re.I))],
    "gfe": [("server", re.compile(r"\bgoogle frontend\b|\bgfe\b", re.I))],
    "cloudflare": [("server", re.compile(r"\bcloudflare\b", re.I)), ("cf-ray", re.compile(r".+", re.I))],
}

PROXY_HINT_HEADERS = [
    "via",
    "x-forwarded-for",
    "x-forwarded-proto",
    "x-forwarded-host",
    "x-forwarded-port",
    "x-real-ip",
    "x-request-id",
    "x-correlation-id",
    "x-envoy-upstream-service-time",
    "x-amzn-trace-id",
    "cf-ray",
    "x-azure-ref",
    "x-served-by",
    "x-cache",
    "x-cache-hits",
]


@dataclass
class FetchResult:
    name: str
    url: str
    host_override: str | None
    status: int | None
    headers: dict
    body_len: int
    body_sha256_2k: str
    elapsed_ms: int
    error: str | None


def is_ip(host: str) -> bool:
    try:
        ipaddress.ip_address(host)
        return True
    except Exception:
        return False


def rand_host() -> str:
    return f"rand-{uuid.uuid4().hex[:10]}.invalid"


def rand_path() -> str:
    tail = "".join(random.choice(string.ascii_lowercase + string.digits) for _ in range(16))
    return f"/__probe__/{tail}"


def normalize_headers(h: dict) -> dict:
    return {k.lower(): v for k, v in (h or {}).items()}


def hash_first_2k(b: bytes) -> str:
    return hashlib.sha256(b[:2048]).hexdigest()


def fetch(name: str, url: str, host_override: str | None, timeout: int, insecure: bool) -> FetchResult:
    headers = {}
    if host_override:
        headers["Host"] = host_override

    t0 = time.time()
    try:
        r = requests.get(url, headers=headers, timeout=timeout, allow_redirects=False, verify=not insecure)
        elapsed_ms = int((time.time() - t0) * 1000)
        hb = r.content or b""
        return FetchResult(
            name=name,
            url=url,
            host_override=host_override,
            status=r.status_code,
            headers=normalize_headers(dict(r.headers)),
            body_len=len(hb),
            body_sha256_2k=hash_first_2k(hb),
            elapsed_ms=elapsed_ms,
            error=None,
        )
    except Exception as e:
        elapsed_ms = int((time.time() - t0) * 1000)
        return FetchResult(
            name=name,
            url=url,
            host_override=host_override,
            status=None,
            headers={},
            body_len=0,
            body_sha256_2k="",
            elapsed_ms=elapsed_ms,
            error=str(e),
        )


def make_url_with_path(original_url: str, new_path: str) -> str:
    p = urlparse(original_url)
    return urlunparse((p.scheme, p.netloc, new_path, p.params, p.query, p.fragment))


def diff(a: FetchResult, b: FetchResult) -> list[str]:
    reasons = []
    if a.error or b.error:
        reasons.append("one probe failed")
        return reasons
    if a.status != b.status:
        reasons.append(f"status differs ({a.status} vs {b.status})")
    if a.body_sha256_2k and b.body_sha256_2k and a.body_sha256_2k != b.body_sha256_2k:
        reasons.append("body differs (hash mismatch)")
    if a.body_len and b.body_len:
        delta = abs(a.body_len - b.body_len) / max(a.body_len, b.body_len)
        if delta >= 0.20:
            reasons.append(f"body size differs ({a.body_len} vs {b.body_len})")
    return reasons


def fingerprint(headers: dict) -> list[str]:
    hits = []
    for product, tests in INGRESS_FINGERPRINTS.items():
        for key, rx in tests:
            if key in headers and rx.search(str(headers[key])):
                hits.append(product)
                break
    out = []
    for h in hits:
        if h not in out:
            out.append(h)
    return out


def proxy_hint_headers(headers: dict) -> list[str]:
    present = []
    for h in PROXY_HINT_HEADERS:
        if h in headers:
            present.append(f"{h}: {headers[h]}")
    return present


def reverse_dns_ptr(ip: str) -> str | None:
    try:
        host, _, _ = socket.gethostbyaddr(ip)
        return host.rstrip(".")
    except Exception:
        return None


def tls_sans(host: str, port: int, timeout: int = 5) -> list[str]:
    # Best-effort: if endpoint supports TLS, pull SAN DNS names.
    # This can help when user gives an IP but the cert reveals the hostname.
    ctx = ssl.create_default_context()
    out = []
    try:
        with socket.create_connection((host, port), timeout=timeout) as sock:
            with ctx.wrap_socket(sock, server_hostname=host) as ssock:
                cert = ssock.getpeercert()
        for typ, val in cert.get("subjectAltName", []):
            if typ == "DNS":
                out.append(val.lower())
    except Exception:
        return []
    # de-dup preserve order
    dedup = []
    for x in out:
        if x not in dedup:
            dedup.append(x)
    return dedup


def pick_best_expected(url: str, candidates: list[str], timeout: int, insecure: bool) -> tuple[str | None, FetchResult | None]:
    if not candidates:
        return None, None
    wrong = fetch("wrong-host", url, host_override=rand_host(), timeout=timeout, insecure=insecure)
    best = None
    best_res = None
    best_score = -1
    for c in candidates:
        r = fetch("expected-host", url, host_override=c, timeout=timeout, insecure=insecure)
        d = diff(r, wrong)
        # Score by number of differences; status change matters most
        score = 0
        if any(x.startswith("status differs") for x in d):
            score += 3
        if any("hash mismatch" in x for x in d):
            score += 2
        if any("body size differs" in x for x in d):
            score += 1
        if score > best_score and not r.error:
            best_score = score
            best = c
            best_res = r
    return best, best_res


def print_result(r: FetchResult):
    print(f"\n[{r.name}]")
    print(f"  url: {r.url}")
    if r.host_override:
        print(f"  host: {r.host_override}")
    if r.error:
        print(f"  ERROR: {r.error}")
        return
    print(f"  status: {r.status}  elapsed: {r.elapsed_ms} ms  body_len: {r.body_len}")
    print(f"  server: {r.headers.get('server','unknown')}")
    hints = proxy_hint_headers(r.headers)
    if hints:
        print("  proxy-hint-headers:")
        for x in hints[:8]:
            print(f"    - {x}")
    fps = fingerprint(r.headers)
    if fps:
        print(f"  fingerprints: {', '.join(fps)}")


def verdict(baseline: FetchResult, wrong_host: FetchResult, root: FetchResult, randp: FetchResult, expected: FetchResult | None):
    score = 0
    reasons = []

    host_diff = diff(baseline, wrong_host)
    if host_diff:
        score += 4
        reasons.append(f"Host sensitivity: {', '.join(host_diff)}")

    path_diff = diff(root, randp)
    if path_diff:
        score += 2
        reasons.append(f"Path sensitivity: {', '.join(path_diff)}")

    fp = fingerprint(baseline.headers)
    if fp:
        score += 2
        reasons.append(f"Fingerprint(s): {', '.join(fp)}")

    hints = proxy_hint_headers(baseline.headers)
    if hints:
        score += 1
        reasons.append("Forwarded/proxy headers present")

    if expected and not expected.error and not wrong_host.error:
        exp_diff = diff(expected, wrong_host)
        if exp_diff:
            score += 4
            reasons.append(f"Expected Host differs from wrong Host: {', '.join(exp_diff)}")

    # Thresholds tuned so your “score=4” becomes MEDIUM
    if score >= 8:
        level = "HIGH"
    elif score >= 4:
        level = "MEDIUM"
    elif score >= 2:
        level = "LOW"
    else:
        level = "INCONCLUSIVE"
    return level, score, reasons


def main():
    ap = argparse.ArgumentParser(description="Infer L7 gateway/Ingress in front (URL only).")
    ap.add_argument("url", help="http(s)://host-or-ip/path")
    ap.add_argument("--timeout", type=int, default=10)
    ap.add_argument("--insecure", action="store_true", help="Disable TLS verification (https only)")
    args = ap.parse_args()

    p = urlparse(args.url)
    if not p.scheme or not p.netloc:
        print("URL must include scheme and host, e.g. http://1.2.3.4/path")
        sys.exit(2)

    host = p.hostname
    if not host:
        print("Could not parse hostname from URL")
        sys.exit(2)

    # Build expected-host candidates automatically
    candidates = []
    if not is_ip(host):
        candidates.append(host.lower())
    else:
        ptr = reverse_dns_ptr(host)
        if ptr:
            candidates.append(ptr.lower())
        if p.scheme == "https":
            # Try SANs from cert (best-effort); may be empty if handshake/cert blocks it
            candidates.extend(tls_sans(host, p.port or 443))

    # Choose best expected host candidate (if any)
    best_expected_host, expected_res = pick_best_expected(args.url, candidates, args.timeout, args.insecure)

    baseline = fetch("baseline", args.url, host_override=None, timeout=args.timeout, insecure=args.insecure)
    wrong_host = fetch("wrong-host", args.url, host_override=rand_host(), timeout=args.timeout, insecure=args.insecure)

    root_url = make_url_with_path(args.url, "/")
    rand_url = make_url_with_path(args.url, rand_path())
    root = fetch("root-path", root_url, host_override=best_expected_host, timeout=args.timeout, insecure=args.insecure)
    randp = fetch("random-path", rand_url, host_override=best_expected_host, timeout=args.timeout, insecure=args.insecure)

    print_result(baseline)
    print_result(wrong_host)
    if best_expected_host:
        # Re-label the chosen expected result for printing clarity
        if expected_res:
            expected_res.name = "expected-host(auto)"
            print_result(expected_res)
        else:
            print("\n[expected-host(auto)]\n  (no successful response)")
    print_result(root)
    print_result(randp)

    level, score, reasons = verdict(baseline, wrong_host, root, randp, expected_res)

    print("\n=== VERDICT ===")
    print(f"Likelihood of L7 gateway/Ingress in front: {level} (score={score}/13)")
    if best_expected_host:
        print(f"Auto expected Host used: {best_expected_host}")
    elif candidates:
        print(f"Expected Host candidates tried (none worked): {', '.join(candidates[:5])}")
    else:
        print("No expected Host could be derived from input.")

    if reasons:
        print("Reasons:")
        for r in reasons:
            print(f" - {r}")

    sys.exit(0 if level in ("HIGH", "MEDIUM") else 1)


if __name__ == "__main__":
    main()
