# Code Generated by Sidekick is for learning and experimentation purposes only.
import requests

PROXY_HINT_HEADERS = [
    "server", "via", "x-forwarded-for", "x-forwarded-proto", "x-forwarded-host",
    "x-request-id", "x-correlation-id", "x-envoy-upstream-service-time",
    "x-amzn-trace-id"
]

def detect_ingress(url, host_header=None, timeout=10):
    headers = {}
    if host_header:
        headers["Host"] = host_header

    r = requests.get(url, headers=headers, timeout=timeout, allow_redirects=False)
    print("Status:", r.status_code)
    print("URL:", url)
    if host_header:
        print("Host header:", host_header)

    # Print only relevant headers (case-insensitive)
    lower_map = {k.lower(): (k, v) for k, v in r.headers.items()}
    for h in PROXY_HINT_HEADERS:
        if h in lower_map:
            orig_k, v = lower_map[h]
            print(f"{orig_k}: {v}")

    # Quick heuristics
    server = lower_map.get("server", ("server", "unknown"))[1].lower()
    if any(x in server for x in ["nginx", "traefik", "istio", "envoy", "awselb", "google frontend"]):
        print("Likely proxy/ingress in front (Server hint).")
    elif any(h in lower_map for h in ["via", "x-forwarded-for", "x-forwarded-proto"]):
        print("Likely proxy/ingress in front (forwarded headers).")
    else:
        print("Not conclusive from headers alone (common).")

# Compare no-host vs host-based routing:
detect_ingress("http://34.59.114.41/web")
detect_ingress("http://34.59.114.41/web", host_header="yourapp.yourdomain.com")
